### ISSUE TITLE
Trying to open files from ext sd gives error

### ISSUE THREAD

**Issue by bkromhout** [bkromhout/Minerva#73]
java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/1D04-1916/Test_ePubs/Fics/A Better Man - Valandar.epub
 at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:678)
 at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:377)
 at com.bkromhout.minerva.data.ActionHelper.openBookUsingIntent(ActionHelper.java:238)
 at com.bkromhout.minerva.fragments.LibraryFragment.onCardClicked(LibraryFragment.java:420)
 at java.lang.reflect.Method.invoke(Native Method)
 at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
 at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:416)
 at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
 at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
 at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
 at com.bkromhout.minerva.adapters.BaseBookCardAdapter.lambda$onBindViewHolder$18(BaseBookCardAdapter.java:106)
 at com.bkromhout.minerva.adapters.BaseBookCardAdapter$$Lambda$1.onClick(Unknown Source)
 at android.view.View.performClick(View.java:5198)
 at android.view.View$PerformClick.run(View.java:21147)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:148)
 at android.app.ActivityThread.main(ActivityThread.java:5417)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by bkromhout** [comment]
Something just isn't right with our file provider. Look into it.

Might need this https://github.com/commonsguy/cwac-provider, we'll see
